robot_name: main_hand

motors:
  valve_ch0:
    driver: generic
    bus: generic_bus
    can_id: 0xC0
    control_type: on_off
    expected_firmware: 2

  valve_ch1:
    driver: generic
    bus: generic_bus
    can_id: 0xC1
    control_type: on_off
    expected_firmware: 2

  valve_ch2:
    driver: generic
    bus: generic_bus
    can_id: 0xC2
    control_type: on_off
    expected_firmware: 2

  valve_ch3:
    driver: generic
    bus: generic_bus
    can_id: 0xC3
    control_type: on_off
    expected_firmware: 2

  valve_ch4:
    driver: generic
    bus: generic_bus
    can_id: 0xC4
    control_type: on_off
    expected_firmware: 2

  valve_ch5:
    driver: generic
    bus: generic_bus
    can_id: 0xC5
    control_type: on_off
    expected_firmware: 2
