robot_name: main_hand

motors:
  rotate_r:
    driver: edulite05
    bus: edulite_bus
    can_id: 1
    host_id: 0xFD
    mode: position
    limit_speed: 1.0
    limit_current: 2.5
    position_kp: 30.0
    set_zero_on_start: true

  rotate_l:
    driver: edulite05
    bus: edulite_bus
    can_id: 2
    host_id: 0xFD
    mode: position
    limit_speed: 1.0
    limit_current: 2.5
    position_kp: 30.0
    set_zero_on_start: true
