robot_name: main_hand

motors:
  y_axis_r:
    driver: m3508
    bus: m3508_bus
    can_id: 1
    pid:
      kp: 32.0
      ki: 10.0
      kd: 1.0
      integral_limit: 1000.0
      dead_band: 1.0
      output_limit: 5000

  y_axis_l:
    driver: m3508
    bus: m3508_bus
    can_id: 2
    pid:
      kp: 32.0
      ki: 10.0
      kd: 1.0
      integral_limit: 1000.0
      dead_band: 1.0
      output_limit: 5000

  rotate_r:
    driver: edulite05
    bus: edulite_bus
    can_id: 1
    host_id: 0xFD
    mode: position
    limit_speed: 2.0
    limit_current: 5.0
    position_kp: 30.0
    set_zero_on_start: true

  rotate_l:
    driver: edulite05
    bus: edulite_bus
    can_id: 2
    host_id: 0xFD
    mode: position
    limit_speed: 2.0
    limit_current: 5.0
    position_kp: 30.0
    set_zero_on_start: true

  gripper:
    driver: generic
    bus: generic_bus
    can_id: 0x40
    control_type: position
    expected_firmware: 5
    expected_angle_range_deg: 270.0

  conveyor:
    driver: generic
    bus: generic_bus
    can_id: 0x80
    control_type: duty
    expected_firmware: 2

  wall_f:
    driver: generic
    bus: generic_bus
    can_id: 0x41
    control_type: position
    expected_firmware: 5
    expected_angle_range_deg: 270.0

  wall_r:
    driver: generic
    bus: generic_bus
    can_id: 0x42
    control_type: position
    expected_firmware: 5
    expected_angle_range_deg: 270.0

sensors:
  rotate_origin_sensor:
    bus: generic_bus
    can_id: 0x43
