robot_name: sub_hand

motors:
  sub_y_axis:
    driver: dm3520
    bus: dm3520_bus
    can_id: 0x01
    master_id: 0x11
    mode: position
    limit_speed: 1.0
    p_max: 12.5
    v_max: 200.0
    t_max: 10.0
    set_zero_on_start: false

  sub_lift:
    driver: dm3520
    bus: dm3520_bus
    can_id: 0x02
    master_id: 0x12
    mode: position
    limit_speed: 1.0
    p_max: 12.5
    v_max: 200.0
    t_max: 10.0
    set_zero_on_start: false
