robot_name: main_hand

motors:
  y_axis_r:
    driver: m3508
    bus: m3508_bus
    can_id: 1
    pid:
      kp: 32.0
      ki: 10.0
      kd: 1.0
      integral_limit: 400.0
      dead_band: 1.0
      output_limit: 800

  y_axis_l:
    driver: m3508
    bus: m3508_bus
    can_id: 2
    pid:
      kp: 32.0
      ki: 10.0
      kd: 1.0
      integral_limit: 400.0
      dead_band: 1.0
      output_limit: 800
